name: Run Cypress Tests on JS Changes

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install
          npm install cypress-html-reporter --save-dev
      - name: Run Cypress tests and generate mochawesome report
        run: |
          mkdir -p html-report
          npx cypress run --reporter cypress-html-reporter --reporter-options "output=html-report/report.html"
      - name: Print merged JSON file contents
        run: |
          cat html-report/report.html || echo "HTML report not found"
      - name: Generate mochawesome HTML report
        run: |
          echo "HTML report generated. Skipping additional generation."
      - name: Upload mochawesome HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: html-report/*.html
