name: Run Cypress Tests on JS Changes

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
  workflow_dispatch:

          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests and save report
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          mkdir -p results
          npx cypress run --reporter junit --reporter-options "mochaFile=results/test_report_$TIMESTAMP.xml"
      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-report
          path: results/
